language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"

install:
    - python setup.py install
    - pip install -r requirements_test.txt

script:
    - ruby --version
    - pep8 sensu_plugin
    - pylint --rcfile=pylint.rc sensu_plugin
    - nosetests --with-coverage --cover-package=sensu_plugin --cover-min-percentage=35 sensu_plugin/test/
